version: "3.9"

networks:

    khyber:

        external: false

        driver: bridge

volumes:

    mariadb:

        external: false

services:

    nginx:

        restart: unless-stopped

        networks:
            - khyber

        ports:
            - "80:80"

        container_name: nginx

        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
            - "./steve.conf:/etc/nginx/conf.d/steve.conf"
            - "./simulator.conf:/etc/nginx/conf.d/simulator.conf"

        image: nginx:1.22.0-alpine

        depends_on:
            - steve

    simulator:

        restart: unless-stopped

        networks:
            - khyber

        # ports:
            # - "80:80"

        container_name: simulator

        image: nginx:1.22.0-alpine

        volumes:
            - "./index.html:/usr/share/nginx/html/index.html"

    mariadb:

        restart: unless-stopped

        networks:
            - khyber

        # ports:
            # - "3306:3306"

        container_name: mariadb

        volumes:
            - "mariadb:/var/lib/mysql"

        image: mariadb:10.8.3

        env_file:
            - mariadb.env

    flyway:

        restart: on-failure

        networks:
            - khyber

        container_name: flyway

        command: migrate

        volumes:
            - "./flyway/sql:/flyway/sql"
            - "./flyway/conf:/flyway/conf"

        image: flyway/flyway:8.5.11-alpine

        depends_on:
            - mariadb

    node-red:

        restart: unless-stopped

        # network_mode: host

        networks:
            - khyber

        ports:
            - "1880:1880"
            - "2200-2300:2200-2300"

        container_name: node-red

        volumes:
            - "./node-red:/data"
            # - "node-red:/data"

        build:
            context: ./node-red

        # image: nodered/node-red:2.2.0
        image: irasus/node-red:22.02.2

        environment:
            - TZ=Asia/Kolkata

    steve:

        restart: unless-stopped

        networks:
            - khyber

        container_name: steve

        # ports:
            # - "80:80"
            # - "443:443"

        build:
            context: .
            dockerfile: Dockerfile.copy

        image: irasus/steve:latest

        depends_on:
            flyway:
                condition: service_completed_successfully
